# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titel',
            new_name='title',
        ),
    ]
